clients:
  accounts:
    url: ${CLIENTS_PROFILE_URL}

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99, 1.00
      percentiles-histogram:
        'http.server.requests': true

  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,refresh"
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=os_auth"
    username: postgres
    password: mysecretpassword
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        default_schema: os_auth
  liquibase:
    database-change-log-lock-table: AUTH_DATABASECHANGELOG_LOCK
    database-change-log-table: AUTH_DATABASECHANGELOG
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.xml
