{
 "title": "online-store dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=~\"online-store-user-chart-.+\"}, pod)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{instance=~\"$instance\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"postgres.*\"},instance)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(pg_up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "fetched",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "returned",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "inserted",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "updated",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deleted",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "QPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$db\",instance=~\"$instance\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "xact_commit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache hit ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"}) / (sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"}) + sum(pg_stat_database_blks_read{datname=~\"$db\",instance=~\"$instance\"}))",
       "legendFormat": "cache hit rate"
      }
     ]
    },
    {
     "title": "Number of active connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{datname=~\"$db\",instance=~\"$instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "conflicts",
       "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deadlocks",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "deadlocks",
       "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "conflicts",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "deadlocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=~'$instance'}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_alloc",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=~'$instance'}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_backend_fsync",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=~'$instance'}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_backend",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=~'$instance'}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_clean",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=~'$instance'}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_checkpoint",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage (All containers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by POD",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=\"$pod\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{pod=~\"online-store-user-chart-deployment.+\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "RPS NGINX overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors Nginx (4**)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4.+\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Errors Nginx (5**)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors (4**)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum by (uri) (increase(http_server_requests_seconds_count{status=~\"4.+\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "ErrorRate (5**)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "sum by (uri) (increase(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency by endpoint (0.5 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.+\", uri!=\"/**\"}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency by endpoint (0.95 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.+\", uri!=\"/**\"}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency by endpoint (0.99 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.+\", uri!=\"/**\"}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency by endpoint (max quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le, uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.+\", uri!=\"/**\"}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (0.5 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency (0.99 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency (0.95 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency (max quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m]))) * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}