apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-chart.fullname" . }}-profiles
data:
  SERVER_PORT: {{ .Values.port.profiles | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres?currentSchema=profiles"
  CLIENTS_AUTH_URL: "http://{{ include "user-chart.fullname" . }}-auth.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.auth.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-chart.fullname" . }}-orders
data:
  SERVER_PORT: {{ .Values.port.orders | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres?currentSchema=app_orders"
  CLIENTS_AUTH_URL: "http://{{ include "user-chart.fullname" . }}-auth.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.auth.port }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-chart.fullname" . }}
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "user-chart.fullname" . }}-auth"
data:
  SERVER_PORT: {{ .Values.port.auth | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres?currentSchema=auth"
  CLIENTS_PROFILE_URL: "http://{{ include "user-chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.profiles.port }}"