apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-chart.fullname" . }}-deployment
  labels:
   {{- include "user-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.profiles.repository }}:{{ .Values.images.profiles.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.profiles.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port.profiles }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-username
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-password
                  optional: false
          envFrom:
            - configMapRef:
                name: {{ include "user-chart.fullname" . }}-profiles
          livenessProbe:
            httpGet:
              port: {{ .Values.port.profiles }}
              path: /actuator/health
            initialDelaySeconds: 100
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-chart.fullname" . }}-deployment-auth
  labels:
   {{- include "user-chart.labels" . | nindent 4 }}-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "user-chart.selectorLabels" . | nindent 6 }}-auth
  template:
    metadata:
      labels:
        {{- include "user-chart.selectorLabels" . | nindent 8 }}-auth
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.auth.repository }}:{{ .Values.images.auth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.auth.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port.auth }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-username
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-password
                  optional: false
          envFrom:
            - configMapRef:
                name: "{{ include "user-chart.fullname" . }}-auth"
          livenessProbe:
            httpGet:
              port: {{ .Values.port.auth }}
              path: /actuator/health
            initialDelaySeconds: 100
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-chart.fullname" . }}-deployment-orders
  labels:
   {{- include "user-chart.labels" . | nindent 4 }}-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "user-chart.selectorLabels" . | nindent 6 }}-orders
  template:
    metadata:
      labels:
        {{- include "user-chart.selectorLabels" . | nindent 8 }}-orders
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.orders.repository }}:{{ .Values.images.orders.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.orders.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port.orders }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-username
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-chart.fullname" . }}
                  key: postgres-password
                  optional: false
          envFrom:
            - configMapRef:
                name: "{{ include "user-chart.fullname" . }}-auth"
          livenessProbe:
            httpGet:
              port: {{ .Values.port.orders }}
              path: /actuator/health
            initialDelaySeconds: 100
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 10
