{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "user-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "user-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 5s
      port: web-billing
      path: /actuator/prometheus
    - interval: 5s
      port: web-orders
      path: /actuator/prometheus
    - interval: 5s
      port: web-products
      path: /actuator/prometheus
    - interval: 5s
      port: web-delivery
      path: /actuator/prometheus
    - interval: 5s
      port: web-notification
      path: /actuator/prometheus
    - interval: 5s
      port: web-auth
      path: /actuator/prometheus
{{- end }}
