apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-billing
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-billing
spec:
  type: {{ .Values.services.billing.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.billing.port }}
      targetPort: {{ .Values.port.billing }}
      name: web-billing
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-billing
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-auth
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-auth
spec:
  type: {{ .Values.services.auth.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.port.auth }}
      name: web-auth
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-auth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-orders
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-orders
spec:
  type: {{ .Values.services.orders.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.orders.port }}
      targetPort: {{ .Values.port.orders }}
      name: web-orders
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-orders
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-products
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-products
spec:
  type: {{ .Values.services.products.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.products.port }}
      targetPort: {{ .Values.port.orders }}
      name: web-products
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-products
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-delivery
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-delivery
spec:
  type: {{ .Values.services.delivery.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.delivery.port }}
      targetPort: {{ .Values.port.delivery }}
      name: web-delivery
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-delivery
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-notification
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-notification
spec:
  type: {{ .Values.services.notification.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.notification.port }}
      targetPort: {{ .Values.port.delivery }}
      name: web-notification
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-notification