management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99, 1.00
      percentiles-histogram:
        'http.server.requests': true

  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,refresh"
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=os_accounts"
    username: postgres
    password: mysecretpassword
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
  liquibase:
    database-change-log-lock-table: ACCOUNTS_DATABASECHANGELOG_LOCK
    database-change-log-table: ACCOUNTS_DATABASECHANGELOG
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${clients.auth.url}/jwks

logging:
  level:
    'org.springframework.web.filter.CommonsRequestLoggingFilter': DEBUG