# Default values for user-chart.
replicaCount: 2

images:
  profiles:
    repository: shaplovdv/profile-service
    pullPolicy: IfNotPresent
    tag: "1.3"
  auth:
    repository: shaplovdv/auth-service
    pullPolicy: IfNotPresent
    tag: "1.8"
  orders:
    repository: shaplovdv/order-service
    pullPolicy: IfNotPresent
    tag: "1.0"

postgresql:
  enabled: true
  username: postgres
  auth:
    postgresPassword: mysecretpassword
  metrics:
    serviceMonitor:
      enabled: true
      interval: 5s
    enabled: true
  global:
    postgresql:
      auth:
        database: postgres

port:
  profiles: "8000"
  auth: "8001"
  orders: "8002"

nameOverride: ""
fullnameOverride: ""

services:
  profiles:
    type: NodePort
    port: 80
  auth:
    type: NodePort
    port: 81
  orders:
    type: NodePort
    port: 82

ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/internal.*" {
          deny all;
          return 403;
        }
  hosts:
    - host: arch.homework
      paths:
        - path: /(.*)
          pathType: Prefix
          serviceSuffix: "-profiles"
          svcPort: 80
        - path: /(.*)
          pathType: Prefix
          serviceSuffix: "-orders"
          svcPort: 82

ingressAuth:
  className: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /(register|login|logout)
          pathType: Prefix
          serviceSuffix: "-auth"
          svcPort: 81

metrics:
  serviceMonitor:
    enabled: true